spring.application.name=api-gateway
#----- manual routing because we have no service discovery (eureka) -----#

# User Service Route (WebFlux)
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# Account Service Route (WebFlux)
spring.cloud.gateway.server.webflux.routes[1].id=account-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/account-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# User Service Route (WebMVC)
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# Account Service Route (WebMVC)
spring.cloud.gateway.server.webmvc.routes[1].id=account-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/account-service/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

server.port=8765

# Debug/inspect routes
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true
logging.level.org.springframework.cloud.gateway=DEBUG
